name = "circleci-scheduler"
main = "worker.js"
compatibility_date = "2024-01-15"

[triggers]
crons = ["0 2 * * *"]  # UTC 2:00 = (Beijing) UTC+8 10:00
# crons = ["0 14 * * *"]  # UTC 14:00 = 多伦多 10:00（夏令时），冬令时为 9:00

[observability.logs]
enabled = true
