version: 2.1

jobs:
  nodeseek:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi
      - run:
          name: Run Nodeseek signin
          command: |
            python -m nodeseek.nodeseek

  v2ex:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi
      - run:
          name: Run V2EX signin
          command: |
            python -m v2ex.v2ex

  onepoint3acres:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests 2captcha-python
      - run:
          name: Debug 1point3acres signin
          command: |
            set -x
            python -m onepoint3acres.onepoint3acres || {
              echo "\n--- FAILURE DIAGNOSTICS ---"
              echo "Check if your credentials or cookies are expired."
              echo "Check if the daily question endpoint or logic has changed."
              exit 1
            }

workflows:
  manual_trigger:
    jobs:
      - nodeseek:
          context: checkincontext
      - v2ex:
          context: checkincontext
      - onepoint3acres:
          context: checkincontext
